### ISSUE TITLE
Data packets planning & Implementation

### ISSUE THREAD

**Issue by inql** [CzolgIT/servertanksgame#9]
I need to plan, which packets do we need (in this case server-side) and implement them.
Will update that issue later on, based on my progress in this milestone.

**Comment by inql** [comment]
partly done, will add more packets if neccessary

**Comment by Matmalecki** [comment]
http://www.gabrielgambetta.com/client-server-game-architecture.html

**Comment by inql** [comment]
still in progress, basic packets are working as expected
